### ISSUE TITLE
lyp installation not complete

### ISSUE THREAD

**Issue by L3br4nd** [noteflakes/lyp#32]
Hi,
I'm trying to use lyp to install lilyjazz under Lubuntu 16.04 but it does not work:
After installing lyp via ruby gem (neither the curl nor the wget installation worked for me, they both aborted with the error: bash: line 52: syntax error: unexpected end of file.| gem required cmake and pkg-config before I could install lyp) I am not able to install any lyp-packages. The installations always abort with the error message:
Could not clone repository (please check that the package URL is correct.)

When I copy the URL into my webbrowser the right git opens so I guess that is not the problem. 

 Opposed to the General spec there is no ~/.lyp/bin folder (.lyp contains the folders ext, lilyponds, packages and a file settings.yml) on my machine also there is no file ~/.bash_profile so I guess that might cause trouble too.

I am not a software developer so I don't know what else you need to help me so feel free to ask.

Thanks, I like the idea of a Lilypond package manager very much

Sven

**Comment by ciconia** [comment]
Thanks Sven for reporting this. The installation script was bad. Please try again and let me know if it works.

**Comment by L3br4nd** [comment]
Hi, 
I tried installing again:
when using gem install lyp it says eveything is fine but the installation takes very short time and nothing seems to have changed.
When using wget I get the following message:
```
Extracting /tmp/lyp-release-installer/release.tar.gz
Could not find rugged-0.23.0 in any of the sources
Run `bundle install` to install missing gems.
user@Notebook-PC:~$ bundle update
Could not locate Gemfile or .bundle/ directory
```
I am now installing rugged manually but as stated in other forums that is not the ideal solution because one should install the required packages to the project and not globally.

**Comment by ciconia** [comment]
Well I found out there's indeed a problem with the rugged gem when installing using the release installation script. However when installing using `gem install lyp` it behaves correctly on my machine. Can you please give me the output of `gem install lyp`?

**Comment by L3br4nd** [comment]
Hi,
it says:
user@Notebook-PC:~$ sudo gem install lyp
[sudo] Passwort für user:
Successfully installed lyp-1.0.0
Parsing documentation for lyp-1.0.0
Done installing documentation for lyp after 2 seconds
1 gem installed
user@Notebook-PC:~$ lyp install lilyjazz
Cloning https://github.com/lyp-packages/lilyjazz.git...
Could not clone repository (please check that the package URL is correct.)
user@Notebook-PC:~$ sudo lyp install lilyjazz
Cloning https://github.com/lyp-packages/lilyjazz.git...
Could not clone repository (please check that the package URL is correct.)

Thanks
Sven

**Comment by ciconia** [comment]
Please run `lyp install -V lilyjazz` and send me the output.

**Comment by L3br4nd** [comment]
user@Notebook-PC:~$ lyp install -V lilyjazz
Cloning https://github.com/lyp-packages/lilyjazz.git...
Could not clone repository (please check that the package URL is correct.)
/var/lib/gems/2.3.0/gems/lyp-1.0.0/lib/lyp/package.rb:241:in `rescue in 
package_repository'
/var/lib/gems/2.3.0/gems/lyp-1.0.0/lib/lyp/package.rb:223:in 
`package_repository'
/var/lib/gems/2.3.0/gems/lyp-1.0.0/lib/lyp/package.rb:143:in 
`install_from_repository'
/var/lib/gems/2.3.0/gems/lyp-1.0.0/lib/lyp/package.rb:65:in `install'
/var/lib/gems/2.3.0/gems/lyp-1.0.0/lib/lyp/cli.rb:173:in `block in install'
/var/lib/gems/2.3.0/gems/lyp-1.0.0/lib/lyp/cli.rb:164:in `each'
/var/lib/gems/2.3.0/gems/lyp-1.0.0/lib/lyp/cli.rb:164:in `install'
/var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 
`invoke_command'
/var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/var/lib/gems/2.3.0/gems/lyp-1.0.0/lib/lyp/cli.rb:323:in `run'
/var/lib/gems/2.3.0/gems/lyp-1.0.0/bin/lyp:9:in `<top (required)>'
/usr/local/bin/lyp:23:in `load'
/usr/local/bin/lyp:23:in `<main>'

**Comment by ciconia** [comment]
OK, this is about the rugged gem. Normally when you install the lyp gem, the rugged gem should also be installed. Can you please check that the rugged gem is installed by running `gem list rugged`?

Also, why do you run `gem install` as sudo?

**Comment by ciconia** [comment]
Sven, you did not reply to my latest comment. Please let me know if you're still having problems.

**Comment by ciconia** [comment]
Closing issue for lack of communication
