### ISSUE TITLE
gem installation failure

### ISSUE THREAD

**Issue by uliska** [noteflakes/lyp#5]
```
~$ sudo gem install lyp
[sudo] password for uliska: 
Fetching: highline-1.7.8.gem (100%)
Successfully installed highline-1.7.8
Fetching: ruby-progressbar-1.7.5.gem (100%)
Successfully installed ruby-progressbar-1.7.5
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: nokogiri-1.6.8.rc2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing lyp:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/nokogiri-1.6.8.rc2 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.8.rc2/gem_make.out
```

It this a missing requirement?

**Comment by ciconia** [comment]
I'm not really a linux guy but you can try to either:

- `apt-get install ruby2.1-dev`
- use [rvm](https://rvm.io/) to install ruby on your system

Let me know if this helps.

**Comment by uliska** [comment]
I suspected this in a way.
Installing the dev package via apt-get brought me further, but I also had to install `cmake` as well. Now the installation process succeeded. 

Obviously there is a set of requirements that is *not* self-explanatory, even for Linux systems with Ruby installed.

**Comment by ciconia** [comment]
I've been meaning to package lyp into a stand-alone release, with pre-compiled ruby and gems. This should take care of any installation problems. Hopefully I'll be able to get it done this weekend.
