### ISSUE TITLE
UTF_8 issues for "roman-numeral" package

### ISSUE THREAD

**Issue by allenloves** [noteflakes/lyp#52]
After installing lilypond with lyp:

When I made /usr/local/bin/lilypond to be the default lilypond version in Frescobaldi, it does not generate any file even after the lilypond log replied compile successful.

When I made ~/.lyp/lilyponds/2.18.2/bin/lilypond  as default version, the compiler does not recognize \require command.

Is there a way to make Frescobaldi to compile with lyp version of lilypond?

**Comment by ciconia** [comment]
I have no experience with Frescobaldi, but you'll need to set it to wherever lyp's lilypond wrapper script resides, depending on lyp was installed. To find it,run:

```bash
$ which lilypond
```

And put the result in Frescobaldi settings.

Let me know if this helps.

**Comment by allenloves** [comment]
I did set it to where the lilypond wrapper script resides
(/usr/local/bin/), and this is the lilypond log I've received when
compiling with frescobaldi.

Starting lilypond 2.18.2 [trashme.ly]...
invalid byte sequence in US-ASCII
Completed successfully in 0.3".

By the way, using the command line in the terminal has no problem.




On Fri, Mar 17, 2017 at 3:37 AM Sharon Rosner <notifications@github.com>
wrote:

I have no experience with Frescobaldi, but you'll need to set it to
wherever lyp's lilypond wrapper script resides, depending on lyp was
installed. To find it,run:

$ which lilypond

And put the result in Frescobaldi settings.

Let me know if this helps.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/noteflakes/lyp/issues/52#issuecomment-287297016>, or mute
the thread

**Comment by ciconia** [comment]
I just installed Frescobaldi 2.2 and successfully compiled a simple file including a `\require` command without any problem. Please try compiling this on your machine:

```lilypond
\require "assert"
#(assert #t)

{ c d e f }
```

**Comment by allenloves** [comment]
Assert works on my machine too (although I don't know what it does).  I
guess the problem is not on the wrapper.


The package I was using is roman-numerals
Here is the example code I was trying to compile:


\require "roman-numerals"

bassline = \relative c' {
  \clef bass
  \key g \major
  \time 3/4
  g4 fis f
  e es es
  d2 dis4
  e2.
  \bar "||"
}

analysis = \lyricmode {
  \override LyricText.self-alignment-X = #-0.6
  \offset StanzaNumber.X-offset #-3
  \set stanza  = #"G:"
  % For bare Roman numerals, \rN simply outputs the string.
  %\markup \rN { I }
  I
  \markup \rN { V 6 5 }
  \markup \rN { vii o 4 3 / IV }
  \markup \rN { IV 6 }
  \markup \rN { ii h 4 3 }
  \markup \rN { Fr +6 }
  \markup \rN { I 6 4 }
  \markup \rN { vii o 7 / vi }
  vi
}

\score {
  \new Staff <<
    \new Voice = "bass" { \bassline }
    \new Lyrics \with {
      % to control distance of analysis from staff
      \override VerticalAxisGroup.nonstaff-relatedstaff-spacing =
#'((basic-distance . 6.5))
    } \lyricsto "bass" { \analysis }
  >>
  \layout {
    \context {
      \Score
      % to control horizontal spacing
      \override SpacingSpanner.shortest-duration-space = #6
    }
    \context {
      \Lyrics
      % to control global size
      %\override LyricText.font-size = #-1
    }
  }
}

**Comment by ciconia** [comment]
It took a while to get to the bottom of this. The problem is that Frescobaldi does not set or pass the `LC_CTYPE` environment variable to the lilypond wrapper, and so the default `US-ASCII` encoding is used. So even if you properly set `LC_CTYPE` in `~/.bash_profile` (or `~/.bashrc` etc), because Frescobaldi is GUI app it will not receive this setting.

If you're on MacOS, run `sudo nano /etc/launchd.conf` and add the following line:

```bash
setenv LC_CTYPE=en_US.UTF-8
```

And you should be good to go (I don't know how this is done on Linux.)

**Comment by allenloves** [comment]
Still no luck.

**Comment by ciconia** [comment]
Please give me some info on your installation:

- OS
- ruby version
- lyp version

**Comment by allenloves** [comment]
OSX 10.11.6
ruby 2.4.0p0
lyp 1.3.5

**Comment by ciconia** [comment]
Did you restart Frescobaldi after editing `/etc/launchd.conf`?

**Comment by allenloves** [comment]
Yes I did.

**Comment by ciconia** [comment]
OK, let's try to patch your lilypond gem wrapper script., Add the following line to `/usr/local/bin/lilypond` (you'll probably need to open it with `sudo` to edit it):

```ruby
Encoding.default_external = Encoding::UTF_8
```
Put this line just after the first ("shebang") line in the script. Let me know if this solves the problem.

**Comment by allenloves** [comment]
It works.
And it's also safe to delete my /etc/launchd.conf which did not exist in
the first place.

Thanks
Allen

**Comment by ciconia** [comment]
OK. I'll try to find a way to detect this automatically without causing problems for users who use encodings other than UTF-8.
