### ISSUE TITLE
Cannot open lyp or lilypond on OSX 10.13.1

### ISSUE THREAD

**Issue by allenloves** [noteflakes/lyp#56]
This is the error message I receive when I try to run lyp or lilypond.  

/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem lyp (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
	from /usr/local/bin/lyp:22:in `<main>'

**Comment by allenloves** [comment]
When I try to reinstall lyp by using sudo gem install lyp, I get this error message:

ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String

**Comment by ciconia** [comment]
When you run lyp please add the --verbose flag to get a backtrace for the error, e.g.:

`lyp install --verbose lilypond`

**Comment by allenloves** [comment]
Here is the error message I've got, it looks the same:

~ mac$ lyp install --verbose lilypond
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem lyp (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
	from /usr/local/bin/lyp:22:in `<main>'

**Comment by ciconia** [comment]
Looking at your other comment above, is there a reason you run `gem` using sudo? In any case you might be able to clean up the mess by running `gem uninstall lyp` and then installing it again.

Personally I use [rvm](https://rvm.io/) to manage my ruby installation, and I don't have any experience with installing ruby using brew, but on my own MacOS 10.13 machine I see no problem installing lyp.

**Comment by andrewcsmith** [comment]
@allenloves that's not the error I'm getting. Looks like yours is related to `lyp` not being installed as a gem in your local ruby installation.

**Comment by andrewcsmith** [comment]
@allenloves It looks like you're having an issue related to [installing Ruby with Homebrew](https://stackoverflow.com/questions/6482738/installing-ruby-gems-not-working-with-home-brew).

The "approved" answer is to use `rvm` (which @ciconia uses) or `rbenv` (which I use), but there are other options that require more manual configuration.

Try running `gem list` and `sudo gem list` to see if they differ, as a start.

(Apologies for the other comment! I had forgotten that I was watching this repo and got my issues mixed up.)

**Comment by allenloves** [comment]
It works.  Thanks.
