### ISSUE TITLE
verbose output is impossible

### ISSUE THREAD

**Issue by andrewcsmith** [noteflakes/lyp#58]
Running `lyp compile --verbose <FILE>` passes the `--verbose` flag onto lyp, rather than lilypond. As a result it's not possible to get a verbose back trace.

**Comment by ciconia** [comment]
Yep, look at my reply to your other issue (#57). You can use `-lDEBUG` instead.

**Comment by andrewcsmith** [comment]
Works for me. It'd be great to make that note in the docs but that's another issue.
